worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    # Rate limiting zone
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1r/s;
    # Proxy cache
    proxy_cache_path cache levels=1:2 keys_zone=my_cache:10m max_size=50m;

    server {
        listen 9090;
        server_name localhost;

        # Users Service
        location /users {
            proxy_pass http://localhost:3001;
            limit_req zone=api_limit burst=5 nodelay;
            proxy_cache my_cache;
            proxy_cache_valid 200 10s;
        }

        # Orders Service
        location /orders {
            proxy_pass http://localhost:3002;
            limit_req zone=api_limit burst=5 nodelay;
            proxy_cache my_cache;
            proxy_cache_valid 200 10s;
        }
    }
}